boxuegu/apps/courses/urls.py
from django.conf.urls import url, include

from courses import views


from courses.views import CourseDetail, CourseList


urlpatterns = [
    url(r'^course/detail/(\d+)/$', views.CourseDetail.as_view(), name='course_detail'),

    # url(r'^org/detail/(\d+)/$', views.OrgDetail.as_view(), name='org_detail'),
    url(r'^course/list/$', views.CourseList.as_view(), name='course_list'),
    url(r'^course/info/(\d+)/$', views.CourseInfo.as_view(), name='course_info'),
    # url(r'^teacher/detail/$', views.TeacherDetail.as_view(), name='teacher_detail'),

]

boxuegu/apps/organization/urls.py
from django.conf.urls import url, include

from organization import views


urlpatterns = [

    url(r'^organization/org/$', views.OrgList.as_view(), name='org_list'),
    url(r'^organization/list/$', views.TeacherList.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(\d+)/$', views.TeacherDetail.as_view(), name='teacher_detail'),
    url(r'^organization/teacher/$', views.OrgTeacher.as_view(), name='org_teacher'),
    url(r'^add/fav/$', views.AddFav.as_view(), name='add_fav'),
    url(r'^organization/home/(\d+)/$', views.OrgHome.as_view(), name='org_home'),
    url(r'^organization/delfav/$', views.DelFav.as_view(), name='del_fav'),
]

boxuegu/apps/users/urls.py
from django.conf.urls import url
from apps.users import views


urlpatterns = [
    # 首页
    url(r'^$', views.IndexView.as_view(), name="index"),
    # 登出
    url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    # 路由名为register
    url(r'^register/$', views.UserRegister.as_view(), name='register'),
    # login
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # course_detail
    url(r'^modify_pwd/$', views.ModifypwdView.as_view(), name="modify_pwd"),
    url(r'^reset/(?P<active_code>.*)/$', views.ResetView.as_view(), name='reset_pwd'),
    url(r'^center/$', views.UserCenterView.as_view(), name='user_center'),
    url(r'^users/info/$', views.UserInfoView.as_view(), name='user_info'),
    url(r'^image/upload/$', views.UploadImageView.as_view(), name='image_upload'),
    url(r'^mycourse/$', views.MyCourseView.as_view(), name='mycourse'),
    # url(r'^course/detail/$', views.CourseDetail.as_view(), name='course_detail'),
    # url(r'^teacher/detail/$', views.TeacherDetail.as_view(), name='teacher_detail'),
    url(r'^myfav/org/$', views.MyFavOrgView.as_view(), name='myfav_org'),
    url(r'^mycourse/$', views.MyCourseView.as_view(), name='mycourse'),
    url(r'^mymessage/$', views.MyMessageView.as_view(), name='mymessage'),
    url(r'^myfav/teacher/$', views.MyFavTeacherView.as_view(), name='myfav_teacher'),
    url(r'^myfav/course/$', views.MyFavCourseView.as_view(), name='myfav_course'),
    url(r'^forget/pwd/$', views.ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^user_pwd/$',views.UserInfoPWD.as_view(), name='user_pwd')
]

boxuegu/boxuegu/urls.py
import xadmin
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),  # 这是生成验证码的图片
    url('^', include('user_test.urls')),
    # 用户
    url('^', include('users.urls', namespace='users')),
    # courses
    url(r'^', include('courses.urls', namespace='courses')),
    # org
    url(r'^', include('organization.urls', namespace='org')),
]

boxuegu/apps/courses/models.py
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher
# Create your models here.


class Course(models.Model):
    """课程信息表"""
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程学校', null=True, blank=True)
    name = models.CharField(max_length=52, verbose_name='课程名字')
    desc =  models.CharField(max_length=300, verbose_name='课程描述')
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True)
    detail = models.TextField(verbose_name='课程详情')
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=2, verbose_name='难度')
    # 使用分钟做后台记录(存储最小单位)前台转换
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟数)')
    # 保存学习人数:点击开始学习才算
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图', max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否是轮播图')
    category = models.CharField(default='后端', max_length=20, verbose_name='课程类别')
    tag = models.CharField(default='', verbose_name='课程标签', max_length=10)
    youneed_konw = models.CharField(default='', max_length=300, verbose_name='课前须知')
    teacher_tell = models.CharField(default='', max_length=300, verbose_name='老师告诉你能学什么')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程章节数的方法
        return self.lesson_set.all().count()

    def get_learn_users(self):
        # 获取学习这门课程的用户
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        verbose_name = u'轮播课程'
        verbose_name_plural = verbose_name
        # 如果不设置 proxy ，就会再生成一个 BannerCourse 数据表
        proxy = True


# 章节信息
class Lesson(models.Model):
    """章节模型"""
    # 因为一个课程对应很多章节。所以在章节表中将课程设置为外键。
    # 作为一个字段来让我们可以知道这个章节对应那个课程
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    """每章视频"""
    # 因为一个章节对应很多视频。所以在视频表中将章节设置为外键。
    # 作为一个字段来存储让我们可以知道这个视频对应哪个章节.
    lesson = models.ForeignKey(Lesson, verbose_name='章节')
    name = models.CharField(max_length=100, verbose_name='视频名')
    url = models.URLField(max_length=200, verbose_name='访问地址', default='www.baidu.com')
    # 使用分钟做后台记录(存储最小单位)前台转换
    learn_times = models.IntegerField(default=0, verbose_name='视频时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """课程资源"""
    # 因为一个课程对应很多资源。所以在课程资源表中将课程设置为外键。
    # 作为一个字段来让我们可以知道这个资源对应那个课程
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='课件名')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

boxuegu/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>{% block title %}学校课程列表 - 博学谷在线网{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block custom_css %}{% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

</head>
<body>
<section class="headerwrap ">
  <header>
    <div class=" header">
      <div class="top">
        <div class="wp">
          <div class="fl"><p>服务电话：<b>010-56288220</b></p></div>
          <!--登录后跳转-->
          {% if request.user.is_authenticated %}
            <div class="personal">
              <dl class="user fr">
                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                <dt><img width="20" height="20" src="/static/media/{{ request.user.image }}"/></dt>
              </dl>
              <div class="userdetail">
                <dl>
                  <dt><img width="80" height="80" src="/static/media/{{ request.user.image }}" /></dt>
                  <dd>
                    <h2>{{ request.user.nick_name }}</h2>
                    <p>{{ request.user.username }}</p>
                  </dd>
                </dl>
                <div class="btn">
                  <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                  <a class="fr" href="{% url 'users:logout' %}">退出</a>
                </div>
              </div>gvv
            </div>
            <a href="">
              <div class="msg-num">
                <span id="MsgNum">{{ request.user.unread_nums }}</span>
              </div>
            </a>
          {% else %}
            <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
            <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
          {% endif %}
        </div>
      </div>

      <div class="middle">
        <div class="wp">
          <a href="{% url 'users:index' %}" ><img class="fl" src="{% static 'images/logo.jpg' %}" id="boxue" width="140px" height="60px"/></a>
          <div class="searchbox fr">
            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
              <ul class="selectMenu" id="jsSelectMenu">
                <li data-value="course">公开课</li>
                <a href="{% url 'org:org_list' %}"><li data-value="org">学校课程</li></a>
                <li data-value="teacher">授课老师</li>
              </ul>
            </div>
            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
          </div>
        </div>
      </div>


      <nav>
        <div class="nav">
          <div class="wp">
            <ul>
              <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'users:index' %}">首页</a></li>
              <li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
                <a href="{% url 'courses:course_list' %}">
                  公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                </a>
              </li>
              <li class="{% ifequal request.path|slice:'12' '/org/teacher' %}active{% endifequal %}">
                <a href="{% url 'org:teacher_list' %}">授课教师</a>
              </li>
              <li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}"><a href="{% url 'org:org_list' %}">授课学校</a></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>
</section>
<!--crumbs start-->

<!--  面包屑 -->
{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'users:index' %}">首页</a>></li>
      <li>学校课程</li>
    </ul>
  </div>
</section>
{% endblock %}

<!-- 页面 body 内容 -->
{% block custom_content %}
{% endblock %}

<!-- Footer -->
<footer>
  <div class="footer">
    <div class="wp">
      <ul class="cont">
        <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
        <li class="code"><img src="{% static 'images/code.png' %}"/>
          <p class="center">扫描关注微信</p></li>
        <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
          <p class="tell">010-56288220</p>
          <p class="time">周一至周日 9:00-18:00</p></li>
      </ul>

    </div>
    <p class="line"></p>
    <div class="wp clear">
      <span class="fl"> 2016 https://www.boxuegu.com/ 博学谷在线-在线学习交流平台 保留所有权利</span>
      <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
    </div>
  </div>
</footer>

<section>
  <ul class="sidebar">
    <li class="qq">
      <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
    </li>
    <li class="totop"></li>
  </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
<script src="{% static 'js/unslider.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js'  %}"></script>
<script src="{% static 'js/deco-common.js' %}"></script>

{% block custom_js %}{% endblock %}
</body>
</html>

boxuegu/templates/course-detail.html
{% extends 'base.html' %}
{% block title %}{{ course.name }}{% endblock %}
{% load staticfiles %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'users:index' %}">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程:{{ course.name }}</a>></li>
                <li>课程详情</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_content %}
<section>
  <div class="wp">
    <div class="groupPurchase_detail detail">
      <div class="toppro">
        <div class="left">
          <div class="picbox">
            <div class="tb-booth tb-pic">
              <img width="440" height="445" src="/static{{ MEDIA_URL }}{{ course.image }}" class="jqzoom"/>
            </div>
          </div>
          <div class="des">
            <h1 title="django 从入门到精通体验开始了">{{ course.name }}</h1>
            <span class="key">{{ course.desc }}</span>
            <div class="prize">
              <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
              <span class="fr">学习人数：{{ course.students }}</span>
            </div>
            <ul class="parameter">
              <li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.learn_times }}</span></li>
              <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.get_zj_nums }}</span></li>
              <li><span class="pram word3">课程类别：</span><span title="">{{ course.category }}</span></li>
              <li class="piclist"><span class="pram word4">学习用户：</span>
                {% for user_course in course.get_learn_users %}
                  <span class="pic"><img width="40" height="40" src="/static{{ MEDIA_URL }}{{ user_course.user.image}}"/></span>
                {% endfor %}

              </li>
            </ul>
            <div class="btns">
              <div class="btn colectgroupbtn" id="jsLeftBtn">
                {% if has_fav_course %}
                  已收藏
                {% else %}
                  收藏
                {% endif %}
              </div>
              <div class="buy btn"><a style="color: white; display: block;" href="{% url 'courses:course_info' course.id %}">开始学习</a></div>
            </div>
          </div>
        </div>
        <div class="right">
          <div class="head">
            <h1>授课学校</h1>
            <p>世界名校，课程权威</p>
          </div>
          <div class="pic">
            <a href="/company/14/">
              <img width="150" height="80" src="/static{{ MEDIA_URL }}{{ course.course_org.image }}"/>
            </a>
          </div>
          <a href="/company/14/">
            <h2 class="center" title="{{ course.course_org.name }}">{{ course.course_org.name }}</h2>
          </a>
          <div class="btn  notlogin" data-favid="14" id="jsRightBtn">
             {% if has_fav_org %}
               已收藏
             {% else %}
               收藏
             {% endif %}
          </div>
          <div class="clear">
            <ul>
              <li>
                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.course_org.course_nums }}</span>
              </li>
              <li>
                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.course_org.get_teacher_nums }}</span>
              </li>
              <li>所在地区：&nbsp;&nbsp;{{ course.course_org.address }}</li>
              <li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                <img title="金牌学校"  src="{% static 'images/gold.png' %}"/>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="wp">
    <div class="list groupPurchase_detail_pro">
      <div class="left layout">
        <div class="head">
          <ul class="tab_header">
            <li class="active">课程详情</li>
          </ul>
        </div>
        <div class="tab_cont tab_cont1">
          <p>{{ course.detail }}</p>
        </div>
        <div class="tab_cont tab_cont2">
          <div class="comment">
            <div class="comenlist">

            </div>
          </div>
        </div>
      </div>
      <div class="right layout">
        <div class="head">相关课程推荐</div>
        <div class="group_recommend">
          {% for relate_course in relate_courses %}
            <dl>
            <dt>
              <a target="_blank" href="">
                <img width="240" height="220" class="scrollLoading" src="/static{{ MEDIA_URL }}{{ relate_course.image }}"/>
              </a>
            </dt>
            <dd>
              <a target="_blank" href=""><h2>{{ relate_course.name }}</h2></a>
              <span class="fl">学习时长：<i class="key">{{ relate_course.learn_times }}</i></span>
            </dd>
          </dl>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block custom_js %}
 <script>
//收藏分享
function add_fav(current_elem, fav_id, fav_type) {
  $.ajax({
    cache: false,
    type: "POST",
    url: "{% url 'org:add_fav' %}",
    data: {'fav_id': fav_id, 'fav_type': fav_type},
    async: true,
    beforeSend: function (xhr, settings) {
        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
    },
    success: function (data) {
      if (data.status == 'fail') {
        if (data.msg == '用户未登录') {
          window.location.href = "{% url 'users:login' %}";
        } else {
          current_elem.text(data.msg)
        }
      } else if (data.status == 'success') {
        current_elem.text(data.msg)
      }
    },
    error: function(error) {
      alert('ajax 请求失败！')
    }
  });
}
// 收藏课程
$('#jsLeftBtn').on('click', function () {
    add_fav($(this), {{ course.id }}, 1);
});

//收藏学校课程
$('#jsRightBtn').on('click', function () {
    add_fav($(this), {{ course.course_org.id }}, 2);
});
</script>
{% endblock %}

boxuegu/templates/login.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>博学谷在线网登录</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="bg" id="dialogBg"></div>
<header>
  <div class="c-box fff-box">
    <div class="wp header-box">
      <p class="fl hd-tips">博学谷在线网，在线学习平台！</p>
      <ul class="fr hd-bar">
        <li>服务电话：<span>010-56288220</span></li>
        <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
        <li><a href="{% url 'users:register' %}">[注册]</a></li>
      </ul>
    </div>
  </div>
</header>
<section>
  <div class="c-box bg-box">
    <div class="login-box clearfix">
      <div class="hd-login clearfix">
        <a class="index-logo" href="{% url 'users:index' %}"></a>
        <h1>用户登录</h1>
        <a class="index-font" href="{% url 'users:index' %}">回到首页</a>
      </div>
      <div class="fl slide">
        <div class="imgslide">
          <ul class="imgs">
            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
          </ul>
        </div>
        <div class="unslider-arrow prev"></div>
        <div class="unslider-arrow next"></div>
      </div>
      <div class="fl form-box">
        <h2>帐号登录</h2>
        <form action="{% url 'users:login' %}" method="post" autocomplete="off">
          <div class="form-group marb20 {% if form_errors.username %} errorput {% endif %}">
            <input name="username" id="username" type="text" placeholder="手机号/邮箱"/>
          </div>
          <div class="form-group marb8 {% if form_errors.password %} errorput {% endif %}">
            <input name="password" id="password_l" type="password" placeholder="请输入您的密码"/>
          </div>
          <div class="error btns login-form-tips" id="jsLoginTips">
            {% for key, error in form_errors.items %}
              {{ error }}
            {% endfor %}
            {% if not form_errors %} {{ msg }} {% endif %}
          </div>
          <span style="color: red">
              {{ error }}
          </span>
          <div class="auto-box marb38">
            <a class="fr" href="{% url 'users:forget_pwd' %}">忘记密码？</a>
          </div>
          <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 "/>
        {% csrf_token %}
        </form>
        <p class="form-p">没有博学谷在线网帐号？<a href="{% url 'users:register' %}">[立即注册]</a></p>
      </div>
    </div>
  </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" ></script>
<script src="{% static 'js/unslider.js' %}" ></script>
<script src="{% static 'js/login.js' %}" ></script>
</body>
</html>

boxuegu/templates/org-detail-homepage.html
{% extends 'org-base.html' %}
{% load staticfiles %}
{% block custom_title %}课程学校首页{% endblock %}
{% block page_path %}课程学校首页{% endblock %}
{% block right_form %}
<div class="right companycenter layout grouping">
  <div class="head">
    <h1>全部课程</h1>
    <a class="green fr more" href="{% url 'org:org_course' org_id %}">查看更多 > </a>
  </div>
  <div class="brief group_list">
    <!-- 全部课程 -->
    {% for course in all_courses %}
    <div class="module1_5 box">
      <a href="{% url 'courses:course_detail' course.id %}"><img width="214" src="/static{{ MEDIA_URL }}{{ course.image }}"/></a>
      <div class="des">
        <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
        <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
        <span class="fr">参加人数：{{ course.students }}</span>
      </div>
      <div class="bottom">
        <span class="fl">{{ course.course_org.name }}</span>
        <span class="star fr notlogin" data-favid="13" data-fav-type="4">{{ course.fav_nums }}</span>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="right companycenter layout">
  <div class="head">
    <h1>学校教师</h1>
    <a class="green fr more" href="{% url 'org:org_teacher' org_id %}">查看更多 > </a>
  </div>
  {% for teacher in all_teachers %}
  <div class="diarys">
    <div class="module5 share company-diary-box" style="padding:10px 0;">
      <a href="{% url 'org:teacher_detail' teacher.id %}" class="left">
        <img class="pic" src="/static{{ MEDIA_URL }}{{ teacher.image }}"/>
        <p>昵称：{{ teacher.name }}</p>
      </a>
      <div class="right">
        <div class="top">
          <div class="fl">
            <a href=""><h1>java开发教程</h1></a>
            <span>发表于：2015-10-12</span>
          </div>
        </div>
        <div class="middle" style="border-bottom:0;">课程介绍</div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="right companycenter layout">
  <div class="head">
    <h1>学校介绍</h1>
    <a class="green fr more" href="{% url 'org:org_desc' org_id %}">查看更多 > </a>
  </div>
  <p class="cont">{{ course_org.desc }}</p>
</div>
{% endblock %}

boxuegu/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>发送邮件成功</title>
</head>
<body>
<h1>邮件已发送，请查收！</h1>
</body>
</html>

boxuegu/templates/usercenter-fav-teacher.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程-博学谷在线网{% endblock %}

{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="{% url 'users:index' %}">首页</a>></li>
      <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
      <li>我的收藏</li>
    </ul>
  </div>
</section>
{% endblock %}

{% block right_content %}
<div class="right">
      <div class="personal_des Releasecont">
        <div class="head">
          <h1>我的收藏</h1>
        </div>
      </div>
      <div class="personal_des permessage">
        <div class="head">
          <ul class="tab_header messagehead">
            <li><a href="{% url 'users:myfav_org' %}">课程学校</a></li>
            <li class="active"><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
            <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
          </ul>
        </div>
        <div class="messagelist">
          {% for teacher in teacher_list %}
          <div class=" butler_list butler-fav-box">
            <dl class="des users">
              <dt>
                <a href="{% url 'org:teacher_detail' teacher.id %}">
                  <img width="100" height="100" src="/static{{ MEDIA_URL }}{{ teacher.image }}"/>
                </a>
              </dt>
              <dd>
                <h1>
                  <a href="{% url 'org:teacher_detail' teacher.id %}">
                    {{ teacher.name }}<span class="key">认证教师</span>
                  </a>
                </h1>
                <ul class="cont clearfix">
                  <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                  <li class="c7">课程数：<span>{{ teacher.get_course_nums }}</span></li>
                </ul>
                <ul class="cont clearfix">
                  <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                  <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                </ul>
              </dd>
              <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
            </dl>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
{% endblock %}
